language: generic

sudo: require
services:
  - docker

before_install:
  - docker build -t saggitarie/docker-react2 -f Dockerfile.dev .

script:
  - docker run -e CI=true saggitarie/docker-react2 npm run test
