language: generic

sudo: require
services:
  - docker

before_install:
  - docker build -t saggitarie/docker-react2 -f Dockerfile.dev .

script:
  - docker run -e CI=true saggitarie/docker-react2 npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-531246779080"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
